version: "3.8"

services:

  backend:
    build:
      context: ../backend
    container_name: buildsmart-backend

    ports:
      - "5000:5000"

    env_file:
      - ../backend/.env

    restart: always

  frontend:
    build:
      context: ../frontend

    container_name: buildsmart-frontend

    ports:
      - "5173:5173"

    restart: always

    depends_on:
      - backend